/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'owner' : Principal,
  'subaccount' : [] | [Uint8Array],
}
export type AdminPool = { 'exchangeIcp' : null } |
  { 'prizePool' : null } |
  { 'treasury' : null } |
  { 'exchangeLucky' : null };
export interface AdminPoolBalances {
  'exchangeIcp' : IcpE8s,
  'prizePool' : Lucky,
  'treasury' : Lucky,
  'exchangeLucky' : Lucky,
}
export type AdminResetOutcome = { 'ok' : AdminResetResult } |
  { 'err' : GameError };
export interface AdminResetResult {
  'playersCleared' : bigint,
  'round' : bigint,
}
export type AdminRoleChangeOutcome = { 'ok' : AdminUserEntry } |
  { 'err' : GameError };
export interface AdminStatus {
  'roundStopped' : boolean,
  'balances' : AdminPoolBalances,
}
export interface AdminUserEntry { 'principal' : Principal, 'role' : UserRole }
export type AdminUserListOutcome = { 'ok' : Array<AdminUserEntry> } |
  { 'err' : GameError };
export type AdminWithdrawOutcome = { 'ok' : AdminWithdrawResult } |
  { 'err' : GameError };
export interface AdminWithdrawResult {
  'pool' : AdminPool,
  'recipient' : Principal,
  'remaining' : bigint,
  'amount' : bigint,
}
export interface Allowance { 'allowance' : Lucky, 'expires_at' : [] | [bigint] }
export interface AllowanceArg { 'account' : Account, 'spender' : Account }
export interface ApproveArg {
  'fee' : [] | [Lucky],
  'memo' : [] | [Uint8Array],
  'from_subaccount' : [] | [Uint8Array],
  'created_at_time' : [] | [bigint],
  'amount' : Lucky,
  'expected_allowance' : [] | [Lucky],
  'expires_at' : [] | [bigint],
  'spender' : Account,
}
export type ApproveError = {
    'GenericError' : { 'message' : string, 'error_code' : bigint }
  } |
  { 'TemporarilyUnavailable' : null } |
  { 'Duplicate' : { 'duplicate_of' : bigint } } |
  { 'BadFee' : { 'expected_fee' : Lucky } } |
  { 'AllowanceChanged' : { 'current_allowance' : Lucky } } |
  { 'CreatedInFuture' : { 'ledger_time' : bigint } } |
  { 'TooOld' : null } |
  { 'Expired' : { 'ledger_time' : bigint } } |
  { 'InsufficientFunds' : { 'balance' : Lucky } };
export type ApproveResult = { 'Ok' : bigint } |
  { 'Err' : ApproveError };
export interface BetHistoryPage {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<BetRecord>,
}
export type BetNumber = Array<Digit>;
export interface BetRecord {
  'cost' : Lucky,
  'ticketCount' : bigint,
  'placedAt' : Timestamp,
  'number' : BetNumber,
  'round' : bigint,
}
export interface BlockPage {
  'nextIndex' : [] | [bigint],
  'transactions' : Array<Transaction>,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface DailyStats {
  'totalBets' : Lucky,
  'totalPayouts' : Lucky,
  'treasuryIncome' : Lucky,
}
export interface DailyStatsEntry { 'date' : string, 'stats' : DailyStats }
export type DailyStatsOutcome = { 'ok' : Array<DailyStatsEntry> } |
  { 'err' : GameError };
export interface DepositAddress {
  'owner' : Principal,
  'subaccount' : Uint8Array,
  'accountText' : string,
}
export type Digit = bigint;
export interface DigitCrowdfund {
  'thresholdReached' : boolean,
  'amount' : Lucky,
  'digit' : Digit,
  'reachedAt' : [] | [Timestamp],
}
export interface DrawResult {
  'winningNumber' : BetNumber,
  'tiers' : Array<TierResult>,
  'callerTier' : [] | [bigint],
  'callerWinnings' : Lucky,
  'round' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface ExchangePoolState {
  'luckyBalance' : Lucky,
  'icpBalance' : IcpE8s,
}
export type GameError = { 'ok' : null } |
  { 'insufficientBalance' : { 'available' : Lucky, 'required' : Lucky } } |
  { 'ledgerUnavailable' : { 'reason' : string } } |
  { 'roundStopped' : null } |
  { 'invalidPosition' : null } |
  { 'poolInsufficient' : { 'token' : string, 'available' : bigint } } |
  { 'invalidBetNumber' : null } |
  { 'amountTooLarge' : { 'max' : bigint } } |
  { 'amountTooSmall' : { 'min' : bigint } } |
  { 'invalidRecipient' : null } |
  { 'rateLimited' : { 'remainingMs' : bigint } } |
  { 'phaseClosed' : { 'required' : Phase, 'current' : Phase } } |
  { 'notRegistered' : null } |
  { 'invalidAmount' : { 'step' : bigint } } |
  { 'roundNotFound' : { 'round' : bigint } };
export interface GameState {
  'winningNumber' : [] | [BetNumber],
  'crowdfundingDeadline' : Timestamp,
  'roundStopped' : boolean,
  'exchangePoolLucky' : Lucky,
  'exchangePoolIcp' : IcpE8s,
  'treasuryBalance' : Lucky,
  'crowdfundTotal' : Lucky,
  'phase' : Phase,
  'totalPrizePool' : Lucky,
  'positions' : Array<PositionCrowdfund>,
  'bettingDeadline' : Timestamp,
  'phaseDeadline' : Timestamp,
  'round' : bigint,
}
export interface GuideText { 'text' : string, 'isSet' : boolean }
export type IcpE8s = bigint;
export interface LedgerBalance { 'fee' : Lucky, 'balance' : Lucky }
export type Lucky = bigint;
export interface MetadataEntry { 'key' : string, 'value' : MetadataValue }
export type MetadataValue = { 'Int' : bigint } |
  { 'Nat' : bigint } |
  { 'Blob' : Uint8Array } |
  { 'Text' : string };
export interface MigrateBalanceArg {
  'owner' : Principal,
  'subaccount' : [] | [Uint8Array],
}
export type MigrateBalanceOutcome = { 'ok' : MigrateBalanceResult } |
  { 'err' : GameError };
export interface MigrateBalanceResult {
  'to' : Account,
  'totalSupply' : Lucky,
  'blockIndex' : bigint,
  'amount' : Lucky,
}
export interface MintArg {
  'to' : Account,
  'memo' : [] | [Uint8Array],
  'amount' : Lucky,
}
export type MintOutcome = { 'ok' : MintResult } |
  { 'err' : GameError };
export interface MintResult {
  'to' : Account,
  'totalSupply' : Lucky,
  'blockIndex' : bigint,
  'amount' : Lucky,
}
export type Phase = { 'betting' : null } |
  { 'crowdfunding' : null } |
  { 'payout' : null } |
  { 'drawing' : null };
export type PlayerIdentity = { 'player' : null } |
  { 'manipulator' : null } |
  { 'conspirator' : null };
export interface PlayerProfile {
  'actionCooldownMs' : bigint,
  'luckyBalance' : Lucky,
  'lastActionAt' : Timestamp,
  'winCount' : bigint,
  'betCount' : bigint,
  'identity' : PlayerIdentity,
}
export type Position = bigint;
export interface PositionBasis {
  'winningAmount' : Lucky,
  'locked' : boolean,
  'winningDigit' : Digit,
  'digitAmounts' : Array<Lucky>,
  'position' : Position,
}
export interface PositionCrowdfund {
  'lockedDigit' : [] | [Digit],
  'digits' : Array<DigitCrowdfund>,
  'leadingDigit' : Digit,
  'position' : Position,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RoundHistoryEntry {
  'winningNumber' : BetNumber,
  'totalDistributed' : Lucky,
  'crowdfundTotal' : Lucky,
  'totalPrizePool' : Lucky,
  'positions' : Array<PositionBasis>,
  'finishedAt' : Timestamp,
  'round' : bigint,
}
export interface SupportedStandard { 'url' : string, 'name' : string }
export interface TierResult {
  'distributed' : Lucky,
  'winningTickets' : bigint,
  'tier' : bigint,
  'payoutPerTicket' : Lucky,
}
export type Timestamp = bigint;
export interface TokenInfo { 'metadata' : TokenMetadata, 'totalSupply' : Lucky }
export interface TokenMetadata {
  'fee' : Lucky,
  'decimals' : number,
  'logo' : string,
  'name' : string,
  'symbol' : string,
}
export interface TopBetNumber { 'ticketCount' : bigint, 'number' : BetNumber }
export interface Transaction {
  'to' : [] | [Account],
  'fee' : Lucky,
  'from' : [] | [Account],
  'kind' : TransactionKind,
  'memo' : [] | [Uint8Array],
  'timestamp' : Timestamp,
  'index' : bigint,
  'amount' : Lucky,
}
export type TransactionKind = { 'transferFrom' : null } |
  { 'mint' : null } |
  { 'approve' : null } |
  { 'transfer' : null };
export interface TransferArg {
  'to' : Account,
  'fee' : [] | [Lucky],
  'memo' : [] | [Uint8Array],
  'from_subaccount' : [] | [Uint8Array],
  'created_at_time' : [] | [bigint],
  'amount' : Lucky,
}
export type TransferAsset = { 'icp' : null } |
  { 'lucky' : null };
export type TransferDirection = { 'incoming' : null } |
  { 'outgoing' : null };
export type TransferError = {
    'GenericError' : { 'message' : string, 'error_code' : bigint }
  } |
  { 'TemporarilyUnavailable' : null } |
  { 'BadBurn' : { 'min_burn_amount' : Lucky } } |
  { 'Duplicate' : { 'duplicate_of' : bigint } } |
  { 'BadFee' : { 'expected_fee' : Lucky } } |
  { 'CreatedInFuture' : { 'ledger_time' : bigint } } |
  { 'TooOld' : null } |
  { 'InsufficientFunds' : { 'balance' : Lucky } };
export interface TransferFromArg {
  'to' : Account,
  'fee' : [] | [Lucky],
  'spender_subaccount' : [] | [Uint8Array],
  'from' : Account,
  'memo' : [] | [Uint8Array],
  'created_at_time' : [] | [bigint],
  'amount' : Lucky,
}
export type TransferFromError = {
    'GenericError' : { 'message' : string, 'error_code' : bigint }
  } |
  { 'TemporarilyUnavailable' : null } |
  { 'InsufficientAllowance' : { 'allowance' : Lucky } } |
  { 'BadBurn' : { 'min_burn_amount' : Lucky } } |
  { 'Duplicate' : { 'duplicate_of' : bigint } } |
  { 'BadFee' : { 'expected_fee' : Lucky } } |
  { 'CreatedInFuture' : { 'ledger_time' : bigint } } |
  { 'TooOld' : null } |
  { 'InsufficientFunds' : { 'balance' : Lucky } };
export type TransferFromResult = { 'Ok' : bigint } |
  { 'Err' : TransferFromError };
export type TransferResult = { 'Ok' : bigint } |
  { 'Err' : TransferError };
export type TransferStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WalletBalances {
  'icpFeeE8s' : IcpE8s,
  'icpE8s' : IcpE8s,
  'lucky' : Lucky,
}
export interface WalletTransferRecord {
  'id' : bigint,
  'fee' : bigint,
  'status' : TransferStatus,
  'direction' : TransferDirection,
  'asset' : TransferAsset,
  'createdAt' : Timestamp,
  'counterparty' : Principal,
  'amount' : bigint,
}
export interface WinHistoryPage {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<WinRecord>,
}
export interface WinRecord {
  'tier' : bigint,
  'claimedAt' : Timestamp,
  'number' : BetNumber,
  'round' : bigint,
  'payout' : Lucky,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Contribute `amount` Lucky to `digit` at `position` (1-3). Crowdfunding
   * / phase only, positive integer multiple of 1, max 100_000 per call.
   */
  'contributeCrowdfund' : ActorMethod<[Position, Digit, Lucky], GameError>,
  /**
   * / Demote a user to `#user`. Admin only.
   */
  'demoteToUser' : ActorMethod<[Principal], AdminRoleChangeOutcome>,
  /**
   * / Fast-forward the round clock so the current round completes its full
   * / cycle. Admin only.
   */
  'devAdvanceRound' : ActorMethod<[], GameError>,
  /**
   * / Credit `amount` Lucky to the caller's own balance. Admin only.
   */
  'devSeedBalance' : ActorMethod<[bigint], GameError>,
  /**
   * / Set the current round's elapsed time to `elapsedNs` for deterministic
   * / testing. Admin only.
   */
  'devSetRoundElapsed' : ActorMethod<[bigint], GameError>,
  /**
   * / Exchange ICP (e8s) for Lucky at the fixed 1 ICP = 1000 Lucky rate.
   * / Minimum 0.1 ICP, must be a multiple of 0.1 ICP, max 10_000 ICP.
   */
  'exchangeIcpToLucky' : ActorMethod<[IcpE8s], GameError>,
  /**
   * / Exchange Lucky for ICP at the fixed rate. Amount must be a positive
   * / multiple of 1000, max 10_000_000 Lucky, with a 3% Lucky fee.
   */
  'exchangeLuckyToIcp' : ActorMethod<[Lucky], GameError>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Admin control snapshot: stopped flag and current pool balances.
   */
  'getAdminStatus' : ActorMethod<[], AdminStatus>,
  /**
   * / Markdown description of the public API: methods, authorization, units,
   * / round lifecycle, polling guidance, retry safety and error variants.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / The caller's own platform role.
   */
  'getCallerRole' : ActorMethod<[], UserRole>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Per-UTC-day statistics for the inclusive range `fromDate..toDate`
   * / (`YYYY-MM-DD`): total bets placed, total payouts distributed and treasury
   * / income from prize-pool cap overflow. Days with no activity are returned
   * / with zero values. Admin only; non-admins receive `#err`.
   */
  'getDailyStats' : ActorMethod<[string, string], DailyStatsOutcome>,
  /**
   * / Caller's own ICP deposit address (canister principal + per-user
   * / subaccount) so the user can receive ICP.
   */
  'getDepositAddress' : ActorMethod<[], DepositAddress>,
  /**
   * / Draw result of a round: winning number, per-tier counts and payouts,
   * / and the caller's own winnings.
   */
  'getDrawResult' : ActorMethod<[bigint], [] | [DrawResult]>,
  /**
   * / Current exchange pool balances (ICP in e8s, Lucky).
   */
  'getExchangePoolState' : ActorMethod<[], ExchangePoolState>,
  /**
   * / Current round state: round number, phase, deadlines, prize pool,
   * / crowdfund total, treasury, exchange pool and per-position crowdfund data.
   */
  'getGameState' : ActorMethod<[], GameState>,
  /**
   * / The saved guide text plus whether an admin has set one. Pure read.
   */
  'getGuideText' : ActorMethod<[], GuideText>,
  /**
   * / The caller's ledger balance plus the ledger fee.
   */
  'getLedgerBalance' : ActorMethod<[], LedgerBalance>,
  /**
   * / One page of the caller's bet history, newest first. `offset` skips that
   * / many newest records; `limit` is capped server-side.
   */
  'getMyBetHistory' : ActorMethod<[bigint, bigint], BetHistoryPage>,
  /**
   * / The caller's own bounded profile: Lucky balance, identity, last action
   * / timestamp, action cooldown, and total bet/win counts. History is read
   * / through the paginated endpoints below.
   */
  'getMyProfile' : ActorMethod<[], PlayerProfile>,
  /**
   * / One page of the caller's win history, newest first. `offset` skips that
   * / many newest records; `limit` is capped server-side.
   */
  'getMyWinHistory' : ActorMethod<[bigint, bigint], WinHistoryPage>,
  /**
   * / Caller's most recent wallet transfer records, newest first (bounded list).
   */
  'getRecentTransfers' : ActorMethod<[], Array<WalletTransferRecord>>,
  /**
   * / Recent completed rounds, newest first.
   */
  'getRoundHistory' : ActorMethod<[bigint], Array<RoundHistoryEntry>>,
  /**
   * / Token snapshot for the admin token panel: metadata plus total supply.
   */
  'getTokenInfo' : ActorMethod<[], TokenInfo>,
  /**
   * / The top-10 most-bet numbers with their ticket counts.
   */
  'getTopBetNumbers' : ActorMethod<[], Array<TopBetNumber>>,
  /**
   * / Current DAO treasury balance in Lucky.
   */
  'getTreasuryBalance' : ActorMethod<[], Lucky>,
  /**
   * / Caller's wallet balances: Lucky plus the real ICP balance held by the
   * / canister on the ICP ledger, and the ledger transfer fee.
   */
  'getWalletBalances' : ActorMethod<[], WalletBalances>,
  /**
   * / Balance of one account.
   */
  'icrc1_balance_of' : ActorMethod<[Account], Lucky>,
  /**
   * / Number of decimals (0).
   */
  'icrc1_decimals' : ActorMethod<[], number>,
  /**
   * / Ledger transfer fee (0).
   */
  'icrc1_fee' : ActorMethod<[], Lucky>,
  /**
   * / Full ICRC-1 metadata map, including `icrc1:logo`.
   */
  'icrc1_metadata' : ActorMethod<[], Array<MetadataEntry>>,
  /**
   * / Token name (`Lucky`).
   */
  'icrc1_name' : ActorMethod<[], string>,
  /**
   * / The standards this ledger supports (ICRC-1 and ICRC-2).
   */
  'icrc1_supported_standards' : ActorMethod<[], Array<SupportedStandard>>,
  /**
   * / Token symbol (`LUCKY`).
   */
  'icrc1_symbol' : ActorMethod<[], string>,
  /**
   * / Cumulative minted supply (uncapped).
   */
  'icrc1_total_supply' : ActorMethod<[], Lucky>,
  /**
   * / Transfer Lucky from the caller's account to `arg.to`.
   */
  'icrc1_transfer' : ActorMethod<[TransferArg], TransferResult>,
  /**
   * / Allowance of `arg.spender` over `arg.account`.
   */
  'icrc2_allowance' : ActorMethod<[AllowanceArg], Allowance>,
  /**
   * / Grant `arg.spender` an allowance over the caller's account.
   */
  'icrc2_approve' : ActorMethod<[ApproveArg], ApproveResult>,
  /**
   * / Move tokens from `arg.from` to `arg.to` under an allowance held by the
   * / caller as spender.
   */
  'icrc2_transfer_from' : ActorMethod<[TransferFromArg], TransferFromResult>,
  /**
   * / A page of the ledger transaction log, optionally filtered to one account.
   */
  'icrc3_get_blocks' : ActorMethod<[bigint, bigint, [] | [Account]], BlockPage>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Deprecated alias: whether the caller is an admin (platform `#admin` role
   * / or canister controller). The frontend should prefer the package's
   * / `isCallerAdmin`.
   */
  'isCallerController' : ActorMethod<[], boolean>,
  /**
   * / List every registered user with their current role. Admin only.
   */
  'listUsers' : ActorMethod<[], AdminUserListOutcome>,
  /**
   * / Migrate one player's internal Lucky balance into the ledger. Admin only.
   */
  'migrateInternalLucky' : ActorMethod<
    [MigrateBalanceArg],
    MigrateBalanceOutcome
  >,
  /**
   * / Mint `arg.amount` Lucky into `arg.to`. Admin only; uncapped.
   */
  'mintLucky' : ActorMethod<[MintArg], MintOutcome>,
  /**
   * / Place `count` tickets on a 7-digit number. 1 Lucky per ticket, betting
   * / phase only.
   */
  'placeBet' : ActorMethod<[BetNumber, bigint], GameError>,
  /**
   * / Place a complex (复式) bet from a per-position selection structure.
   * / `selections` holds one array of selected digits per position (7 positions)
   * / and `counts` the number of selected digits per position; the total ticket
   * / count is the product of the per-position counts. The backend expands the
   * / cartesian product itself, so the frontend never materializes it. One
   * / 3-second cooldown and one summed deduction, exactly like `placeBets`.
   */
  'placeBetSelections' : ActorMethod<
    [Array<Array<Digit>>, Array<bigint>],
    GameError
  >,
  /**
   * / Place several distinct 7-digit numbers in one call, each with its own
   * / ticket count. A complex (复式) submission is sent here as a single game
   * / action: one 3-second cooldown, one summed deduction into the prize pool.
   * / `numbers` and `counts` must be the same length; each count must be >= 1.
   */
  'placeBets' : ActorMethod<[Array<BetNumber>, Array<bigint>], GameError>,
  /**
   * / Promote a user to `#admin`. Admin only.
   */
  'promoteToAdmin' : ActorMethod<[Principal], AdminRoleChangeOutcome>,
  /**
   * / Reset all game data back to its initial state. Admin only.
   */
  'resetGameData' : ActorMethod<[], AdminResetOutcome>,
  /**
   * / Resume a stopped round. Admin only.
   */
  'resumeRound' : ActorMethod<[], GameError>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Save the guide text. Admin only.
   */
  'setGuideText' : ActorMethod<[string], GameError>,
  /**
   * / Stop the current/next round: no new bets and no crowdfund contributions
   * / until an admin resumes. Admin only.
   */
  'stopNextRound' : ActorMethod<[], GameError>,
  /**
   * / Send ICP (e8s) from the caller's balance to an arbitrary recipient
   * / principal, validating the balance and the ledger transfer fee.
   */
  'transferIcp' : ActorMethod<[Principal, IcpE8s], GameError>,
  /**
   * / Transfer Lucky from the caller's balance to another principal.
   */
  'transferLucky' : ActorMethod<[Principal, Lucky], GameError>,
  /**
   * / Withdraw `amount` from `pool` to `recipient`. Admin only.
   */
  'withdrawFromPool' : ActorMethod<
    [AdminPool, bigint, Principal],
    AdminWithdrawOutcome
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];