/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Position = IDL.Nat;
export const Digit = IDL.Nat;
export const Lucky = IDL.Nat;
export const Phase = IDL.Variant({
  'betting' : IDL.Null,
  'crowdfunding' : IDL.Null,
  'payout' : IDL.Null,
  'drawing' : IDL.Null,
});
export const GameError = IDL.Variant({
  'ok' : IDL.Null,
  'insufficientBalance' : IDL.Record({
    'available' : Lucky,
    'required' : Lucky,
  }),
  'ledgerUnavailable' : IDL.Record({ 'reason' : IDL.Text }),
  'roundStopped' : IDL.Null,
  'invalidPosition' : IDL.Null,
  'poolInsufficient' : IDL.Record({
    'token' : IDL.Text,
    'available' : IDL.Nat,
  }),
  'invalidBetNumber' : IDL.Null,
  'amountTooLarge' : IDL.Record({ 'max' : IDL.Nat }),
  'amountTooSmall' : IDL.Record({ 'min' : IDL.Nat }),
  'invalidRecipient' : IDL.Null,
  'rateLimited' : IDL.Record({ 'remainingMs' : IDL.Nat }),
  'phaseClosed' : IDL.Record({ 'required' : Phase, 'current' : Phase }),
  'notRegistered' : IDL.Null,
  'invalidAmount' : IDL.Record({ 'step' : IDL.Nat }),
  'roundNotFound' : IDL.Record({ 'round' : IDL.Nat }),
});
export const AdminUserEntry = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
});
export const AdminRoleChangeOutcome = IDL.Variant({
  'ok' : AdminUserEntry,
  'err' : GameError,
});
export const IcpE8s = IDL.Nat;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AdminPoolBalances = IDL.Record({
  'exchangeIcp' : IcpE8s,
  'prizePool' : Lucky,
  'treasury' : Lucky,
  'exchangeLucky' : Lucky,
});
export const AdminStatus = IDL.Record({
  'roundStopped' : IDL.Bool,
  'balances' : AdminPoolBalances,
});
export const DailyStats = IDL.Record({
  'totalBets' : Lucky,
  'totalPayouts' : Lucky,
  'treasuryIncome' : Lucky,
});
export const DailyStatsEntry = IDL.Record({
  'date' : IDL.Text,
  'stats' : DailyStats,
});
export const DailyStatsOutcome = IDL.Variant({
  'ok' : IDL.Vec(DailyStatsEntry),
  'err' : GameError,
});
export const DepositAddress = IDL.Record({
  'owner' : IDL.Principal,
  'subaccount' : IDL.Vec(IDL.Nat8),
  'accountText' : IDL.Text,
});
export const BetNumber = IDL.Vec(Digit);
export const TierResult = IDL.Record({
  'distributed' : Lucky,
  'winningTickets' : IDL.Nat,
  'tier' : IDL.Nat,
  'payoutPerTicket' : Lucky,
});
export const DrawResult = IDL.Record({
  'winningNumber' : BetNumber,
  'tiers' : IDL.Vec(TierResult),
  'callerTier' : IDL.Opt(IDL.Nat),
  'callerWinnings' : Lucky,
  'round' : IDL.Nat,
});
export const ExchangePoolState = IDL.Record({
  'luckyBalance' : Lucky,
  'icpBalance' : IcpE8s,
});
export const Timestamp = IDL.Int;
export const DigitCrowdfund = IDL.Record({
  'thresholdReached' : IDL.Bool,
  'amount' : Lucky,
  'digit' : Digit,
  'reachedAt' : IDL.Opt(Timestamp),
});
export const PositionCrowdfund = IDL.Record({
  'lockedDigit' : IDL.Opt(Digit),
  'digits' : IDL.Vec(DigitCrowdfund),
  'leadingDigit' : Digit,
  'position' : Position,
});
export const GameState = IDL.Record({
  'winningNumber' : IDL.Opt(BetNumber),
  'crowdfundingDeadline' : Timestamp,
  'roundStopped' : IDL.Bool,
  'exchangePoolLucky' : Lucky,
  'exchangePoolIcp' : IcpE8s,
  'treasuryBalance' : Lucky,
  'crowdfundTotal' : Lucky,
  'phase' : Phase,
  'totalPrizePool' : Lucky,
  'positions' : IDL.Vec(PositionCrowdfund),
  'bettingDeadline' : Timestamp,
  'phaseDeadline' : Timestamp,
  'round' : IDL.Nat,
});
export const GuideText = IDL.Record({ 'text' : IDL.Text, 'isSet' : IDL.Bool });
export const LedgerBalance = IDL.Record({ 'fee' : Lucky, 'balance' : Lucky });
export const BetRecord = IDL.Record({
  'cost' : Lucky,
  'ticketCount' : IDL.Nat,
  'placedAt' : Timestamp,
  'number' : BetNumber,
  'round' : IDL.Nat,
});
export const BetHistoryPage = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(BetRecord),
});
export const PlayerIdentity = IDL.Variant({
  'player' : IDL.Null,
  'manipulator' : IDL.Null,
  'conspirator' : IDL.Null,
});
export const PlayerProfile = IDL.Record({
  'actionCooldownMs' : IDL.Nat,
  'luckyBalance' : Lucky,
  'lastActionAt' : Timestamp,
  'winCount' : IDL.Nat,
  'betCount' : IDL.Nat,
  'identity' : PlayerIdentity,
});
export const WinRecord = IDL.Record({
  'tier' : IDL.Nat,
  'claimedAt' : Timestamp,
  'number' : BetNumber,
  'round' : IDL.Nat,
  'payout' : Lucky,
});
export const WinHistoryPage = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(WinRecord),
});
export const TransferStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransferDirection = IDL.Variant({
  'incoming' : IDL.Null,
  'outgoing' : IDL.Null,
});
export const TransferAsset = IDL.Variant({
  'icp' : IDL.Null,
  'lucky' : IDL.Null,
});
export const WalletTransferRecord = IDL.Record({
  'id' : IDL.Nat,
  'fee' : IDL.Nat,
  'status' : TransferStatus,
  'direction' : TransferDirection,
  'asset' : TransferAsset,
  'createdAt' : Timestamp,
  'counterparty' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const PositionBasis = IDL.Record({
  'winningAmount' : Lucky,
  'locked' : IDL.Bool,
  'winningDigit' : Digit,
  'digitAmounts' : IDL.Vec(Lucky),
  'position' : Position,
});
export const RoundHistoryEntry = IDL.Record({
  'winningNumber' : BetNumber,
  'totalDistributed' : Lucky,
  'crowdfundTotal' : Lucky,
  'totalPrizePool' : Lucky,
  'positions' : IDL.Vec(PositionBasis),
  'finishedAt' : Timestamp,
  'round' : IDL.Nat,
});
export const TokenMetadata = IDL.Record({
  'fee' : Lucky,
  'decimals' : IDL.Nat8,
  'logo' : IDL.Text,
  'name' : IDL.Text,
  'symbol' : IDL.Text,
});
export const TokenInfo = IDL.Record({
  'metadata' : TokenMetadata,
  'totalSupply' : Lucky,
});
export const TopBetNumber = IDL.Record({
  'ticketCount' : IDL.Nat,
  'number' : BetNumber,
});
export const WalletBalances = IDL.Record({
  'icpFeeE8s' : IcpE8s,
  'icpE8s' : IcpE8s,
  'lucky' : Lucky,
});
export const Account = IDL.Record({
  'owner' : IDL.Principal,
  'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const MetadataValue = IDL.Variant({
  'Int' : IDL.Int,
  'Nat' : IDL.Nat,
  'Blob' : IDL.Vec(IDL.Nat8),
  'Text' : IDL.Text,
});
export const MetadataEntry = IDL.Record({
  'key' : IDL.Text,
  'value' : MetadataValue,
});
export const SupportedStandard = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
});
export const TransferArg = IDL.Record({
  'to' : Account,
  'fee' : IDL.Opt(Lucky),
  'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'from_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'created_at_time' : IDL.Opt(IDL.Nat64),
  'amount' : Lucky,
});
export const TransferError = IDL.Variant({
  'GenericError' : IDL.Record({ 'message' : IDL.Text, 'error_code' : IDL.Nat }),
  'TemporarilyUnavailable' : IDL.Null,
  'BadBurn' : IDL.Record({ 'min_burn_amount' : Lucky }),
  'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
  'BadFee' : IDL.Record({ 'expected_fee' : Lucky }),
  'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
  'TooOld' : IDL.Null,
  'InsufficientFunds' : IDL.Record({ 'balance' : Lucky }),
});
export const TransferResult = IDL.Variant({
  'Ok' : IDL.Nat,
  'Err' : TransferError,
});
export const AllowanceArg = IDL.Record({
  'account' : Account,
  'spender' : Account,
});
export const Allowance = IDL.Record({
  'allowance' : Lucky,
  'expires_at' : IDL.Opt(IDL.Nat64),
});
export const ApproveArg = IDL.Record({
  'fee' : IDL.Opt(Lucky),
  'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'from_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'created_at_time' : IDL.Opt(IDL.Nat64),
  'amount' : Lucky,
  'expected_allowance' : IDL.Opt(Lucky),
  'expires_at' : IDL.Opt(IDL.Nat64),
  'spender' : Account,
});
export const ApproveError = IDL.Variant({
  'GenericError' : IDL.Record({ 'message' : IDL.Text, 'error_code' : IDL.Nat }),
  'TemporarilyUnavailable' : IDL.Null,
  'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
  'BadFee' : IDL.Record({ 'expected_fee' : Lucky }),
  'AllowanceChanged' : IDL.Record({ 'current_allowance' : Lucky }),
  'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
  'TooOld' : IDL.Null,
  'Expired' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
  'InsufficientFunds' : IDL.Record({ 'balance' : Lucky }),
});
export const ApproveResult = IDL.Variant({
  'Ok' : IDL.Nat,
  'Err' : ApproveError,
});
export const TransferFromArg = IDL.Record({
  'to' : Account,
  'fee' : IDL.Opt(Lucky),
  'spender_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'from' : Account,
  'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'created_at_time' : IDL.Opt(IDL.Nat64),
  'amount' : Lucky,
});
export const TransferFromError = IDL.Variant({
  'GenericError' : IDL.Record({ 'message' : IDL.Text, 'error_code' : IDL.Nat }),
  'TemporarilyUnavailable' : IDL.Null,
  'InsufficientAllowance' : IDL.Record({ 'allowance' : Lucky }),
  'BadBurn' : IDL.Record({ 'min_burn_amount' : Lucky }),
  'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
  'BadFee' : IDL.Record({ 'expected_fee' : Lucky }),
  'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
  'TooOld' : IDL.Null,
  'InsufficientFunds' : IDL.Record({ 'balance' : Lucky }),
});
export const TransferFromResult = IDL.Variant({
  'Ok' : IDL.Nat,
  'Err' : TransferFromError,
});
export const TransactionKind = IDL.Variant({
  'transferFrom' : IDL.Null,
  'mint' : IDL.Null,
  'approve' : IDL.Null,
  'transfer' : IDL.Null,
});
export const Transaction = IDL.Record({
  'to' : IDL.Opt(Account),
  'fee' : Lucky,
  'from' : IDL.Opt(Account),
  'kind' : TransactionKind,
  'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'timestamp' : Timestamp,
  'index' : IDL.Nat,
  'amount' : Lucky,
});
export const BlockPage = IDL.Record({
  'nextIndex' : IDL.Opt(IDL.Nat),
  'transactions' : IDL.Vec(Transaction),
});
export const AdminUserListOutcome = IDL.Variant({
  'ok' : IDL.Vec(AdminUserEntry),
  'err' : GameError,
});
export const MigrateBalanceArg = IDL.Record({
  'owner' : IDL.Principal,
  'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const MigrateBalanceResult = IDL.Record({
  'to' : Account,
  'totalSupply' : Lucky,
  'blockIndex' : IDL.Nat,
  'amount' : Lucky,
});
export const MigrateBalanceOutcome = IDL.Variant({
  'ok' : MigrateBalanceResult,
  'err' : GameError,
});
export const MintArg = IDL.Record({
  'to' : Account,
  'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'amount' : Lucky,
});
export const MintResult = IDL.Record({
  'to' : Account,
  'totalSupply' : Lucky,
  'blockIndex' : IDL.Nat,
  'amount' : Lucky,
});
export const MintOutcome = IDL.Variant({
  'ok' : MintResult,
  'err' : GameError,
});
export const AdminResetResult = IDL.Record({
  'playersCleared' : IDL.Nat,
  'round' : IDL.Nat,
});
export const AdminResetOutcome = IDL.Variant({
  'ok' : AdminResetResult,
  'err' : GameError,
});
export const AdminPool = IDL.Variant({
  'exchangeIcp' : IDL.Null,
  'prizePool' : IDL.Null,
  'treasury' : IDL.Null,
  'exchangeLucky' : IDL.Null,
});
export const AdminWithdrawResult = IDL.Record({
  'pool' : AdminPool,
  'recipient' : IDL.Principal,
  'remaining' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const AdminWithdrawOutcome = IDL.Variant({
  'ok' : AdminWithdrawResult,
  'err' : GameError,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'contributeCrowdfund' : IDL.Func([Position, Digit, Lucky], [GameError], []),
  'demoteToUser' : IDL.Func([IDL.Principal], [AdminRoleChangeOutcome], []),
  'devAdvanceRound' : IDL.Func([], [GameError], []),
  'devSeedBalance' : IDL.Func([IDL.Nat], [GameError], []),
  'devSetRoundElapsed' : IDL.Func([IDL.Int], [GameError], []),
  'exchangeIcpToLucky' : IDL.Func([IcpE8s], [GameError], []),
  'exchangeLuckyToIcp' : IDL.Func([Lucky], [GameError], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAdminStatus' : IDL.Func([], [AdminStatus], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyStats' : IDL.Func(
      [IDL.Text, IDL.Text],
      [DailyStatsOutcome],
      ['query'],
    ),
  'getDepositAddress' : IDL.Func([], [DepositAddress], ['query']),
  'getDrawResult' : IDL.Func([IDL.Nat], [IDL.Opt(DrawResult)], ['query']),
  'getExchangePoolState' : IDL.Func([], [ExchangePoolState], ['query']),
  'getGameState' : IDL.Func([], [GameState], ['query']),
  'getGuideText' : IDL.Func([], [GuideText], ['query']),
  'getLedgerBalance' : IDL.Func([], [LedgerBalance], ['query']),
  'getMyBetHistory' : IDL.Func([IDL.Nat, IDL.Nat], [BetHistoryPage], ['query']),
  'getMyProfile' : IDL.Func([], [PlayerProfile], ['query']),
  'getMyWinHistory' : IDL.Func([IDL.Nat, IDL.Nat], [WinHistoryPage], ['query']),
  'getRecentTransfers' : IDL.Func(
      [],
      [IDL.Vec(WalletTransferRecord)],
      ['query'],
    ),
  'getRoundHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RoundHistoryEntry)],
      ['query'],
    ),
  'getTokenInfo' : IDL.Func([], [TokenInfo], ['query']),
  'getTopBetNumbers' : IDL.Func([], [IDL.Vec(TopBetNumber)], ['query']),
  'getTreasuryBalance' : IDL.Func([], [Lucky], ['query']),
  'getWalletBalances' : IDL.Func([], [WalletBalances], []),
  'icrc1_balance_of' : IDL.Func([Account], [Lucky], ['query']),
  'icrc1_decimals' : IDL.Func([], [IDL.Nat8], ['query']),
  'icrc1_fee' : IDL.Func([], [Lucky], ['query']),
  'icrc1_metadata' : IDL.Func([], [IDL.Vec(MetadataEntry)], ['query']),
  'icrc1_name' : IDL.Func([], [IDL.Text], ['query']),
  'icrc1_supported_standards' : IDL.Func(
      [],
      [IDL.Vec(SupportedStandard)],
      ['query'],
    ),
  'icrc1_symbol' : IDL.Func([], [IDL.Text], ['query']),
  'icrc1_total_supply' : IDL.Func([], [Lucky], ['query']),
  'icrc1_transfer' : IDL.Func([TransferArg], [TransferResult], []),
  'icrc2_allowance' : IDL.Func([AllowanceArg], [Allowance], ['query']),
  'icrc2_approve' : IDL.Func([ApproveArg], [ApproveResult], []),
  'icrc2_transfer_from' : IDL.Func([TransferFromArg], [TransferFromResult], []),
  'icrc3_get_blocks' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(Account)],
      [BlockPage],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerController' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([], [AdminUserListOutcome], ['query']),
  'migrateInternalLucky' : IDL.Func(
      [MigrateBalanceArg],
      [MigrateBalanceOutcome],
      [],
    ),
  'mintLucky' : IDL.Func([MintArg], [MintOutcome], []),
  'placeBet' : IDL.Func([BetNumber, IDL.Nat], [GameError], []),
  'placeBetSelections' : IDL.Func(
      [IDL.Vec(IDL.Vec(Digit)), IDL.Vec(IDL.Nat)],
      [GameError],
      [],
    ),
  'placeBets' : IDL.Func(
      [IDL.Vec(BetNumber), IDL.Vec(IDL.Nat)],
      [GameError],
      [],
    ),
  'promoteToAdmin' : IDL.Func([IDL.Principal], [AdminRoleChangeOutcome], []),
  'resetGameData' : IDL.Func([], [AdminResetOutcome], []),
  'resumeRound' : IDL.Func([], [GameError], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setGuideText' : IDL.Func([IDL.Text], [GameError], []),
  'stopNextRound' : IDL.Func([], [GameError], []),
  'transferIcp' : IDL.Func([IDL.Principal, IcpE8s], [GameError], []),
  'transferLucky' : IDL.Func([IDL.Principal, Lucky], [GameError], []),
  'withdrawFromPool' : IDL.Func(
      [AdminPool, IDL.Nat, IDL.Principal],
      [AdminWithdrawOutcome],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Position = IDL.Nat;
  const Digit = IDL.Nat;
  const Lucky = IDL.Nat;
  const Phase = IDL.Variant({
    'betting' : IDL.Null,
    'crowdfunding' : IDL.Null,
    'payout' : IDL.Null,
    'drawing' : IDL.Null,
  });
  const GameError = IDL.Variant({
    'ok' : IDL.Null,
    'insufficientBalance' : IDL.Record({
      'available' : Lucky,
      'required' : Lucky,
    }),
    'ledgerUnavailable' : IDL.Record({ 'reason' : IDL.Text }),
    'roundStopped' : IDL.Null,
    'invalidPosition' : IDL.Null,
    'poolInsufficient' : IDL.Record({
      'token' : IDL.Text,
      'available' : IDL.Nat,
    }),
    'invalidBetNumber' : IDL.Null,
    'amountTooLarge' : IDL.Record({ 'max' : IDL.Nat }),
    'amountTooSmall' : IDL.Record({ 'min' : IDL.Nat }),
    'invalidRecipient' : IDL.Null,
    'rateLimited' : IDL.Record({ 'remainingMs' : IDL.Nat }),
    'phaseClosed' : IDL.Record({ 'required' : Phase, 'current' : Phase }),
    'notRegistered' : IDL.Null,
    'invalidAmount' : IDL.Record({ 'step' : IDL.Nat }),
    'roundNotFound' : IDL.Record({ 'round' : IDL.Nat }),
  });
  const AdminUserEntry = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
  });
  const AdminRoleChangeOutcome = IDL.Variant({
    'ok' : AdminUserEntry,
    'err' : GameError,
  });
  const IcpE8s = IDL.Nat;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AdminPoolBalances = IDL.Record({
    'exchangeIcp' : IcpE8s,
    'prizePool' : Lucky,
    'treasury' : Lucky,
    'exchangeLucky' : Lucky,
  });
  const AdminStatus = IDL.Record({
    'roundStopped' : IDL.Bool,
    'balances' : AdminPoolBalances,
  });
  const DailyStats = IDL.Record({
    'totalBets' : Lucky,
    'totalPayouts' : Lucky,
    'treasuryIncome' : Lucky,
  });
  const DailyStatsEntry = IDL.Record({
    'date' : IDL.Text,
    'stats' : DailyStats,
  });
  const DailyStatsOutcome = IDL.Variant({
    'ok' : IDL.Vec(DailyStatsEntry),
    'err' : GameError,
  });
  const DepositAddress = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Vec(IDL.Nat8),
    'accountText' : IDL.Text,
  });
  const BetNumber = IDL.Vec(Digit);
  const TierResult = IDL.Record({
    'distributed' : Lucky,
    'winningTickets' : IDL.Nat,
    'tier' : IDL.Nat,
    'payoutPerTicket' : Lucky,
  });
  const DrawResult = IDL.Record({
    'winningNumber' : BetNumber,
    'tiers' : IDL.Vec(TierResult),
    'callerTier' : IDL.Opt(IDL.Nat),
    'callerWinnings' : Lucky,
    'round' : IDL.Nat,
  });
  const ExchangePoolState = IDL.Record({
    'luckyBalance' : Lucky,
    'icpBalance' : IcpE8s,
  });
  const Timestamp = IDL.Int;
  const DigitCrowdfund = IDL.Record({
    'thresholdReached' : IDL.Bool,
    'amount' : Lucky,
    'digit' : Digit,
    'reachedAt' : IDL.Opt(Timestamp),
  });
  const PositionCrowdfund = IDL.Record({
    'lockedDigit' : IDL.Opt(Digit),
    'digits' : IDL.Vec(DigitCrowdfund),
    'leadingDigit' : Digit,
    'position' : Position,
  });
  const GameState = IDL.Record({
    'winningNumber' : IDL.Opt(BetNumber),
    'crowdfundingDeadline' : Timestamp,
    'roundStopped' : IDL.Bool,
    'exchangePoolLucky' : Lucky,
    'exchangePoolIcp' : IcpE8s,
    'treasuryBalance' : Lucky,
    'crowdfundTotal' : Lucky,
    'phase' : Phase,
    'totalPrizePool' : Lucky,
    'positions' : IDL.Vec(PositionCrowdfund),
    'bettingDeadline' : Timestamp,
    'phaseDeadline' : Timestamp,
    'round' : IDL.Nat,
  });
  const GuideText = IDL.Record({ 'text' : IDL.Text, 'isSet' : IDL.Bool });
  const LedgerBalance = IDL.Record({ 'fee' : Lucky, 'balance' : Lucky });
  const BetRecord = IDL.Record({
    'cost' : Lucky,
    'ticketCount' : IDL.Nat,
    'placedAt' : Timestamp,
    'number' : BetNumber,
    'round' : IDL.Nat,
  });
  const BetHistoryPage = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(BetRecord),
  });
  const PlayerIdentity = IDL.Variant({
    'player' : IDL.Null,
    'manipulator' : IDL.Null,
    'conspirator' : IDL.Null,
  });
  const PlayerProfile = IDL.Record({
    'actionCooldownMs' : IDL.Nat,
    'luckyBalance' : Lucky,
    'lastActionAt' : Timestamp,
    'winCount' : IDL.Nat,
    'betCount' : IDL.Nat,
    'identity' : PlayerIdentity,
  });
  const WinRecord = IDL.Record({
    'tier' : IDL.Nat,
    'claimedAt' : Timestamp,
    'number' : BetNumber,
    'round' : IDL.Nat,
    'payout' : Lucky,
  });
  const WinHistoryPage = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(WinRecord),
  });
  const TransferStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransferDirection = IDL.Variant({
    'incoming' : IDL.Null,
    'outgoing' : IDL.Null,
  });
  const TransferAsset = IDL.Variant({ 'icp' : IDL.Null, 'lucky' : IDL.Null });
  const WalletTransferRecord = IDL.Record({
    'id' : IDL.Nat,
    'fee' : IDL.Nat,
    'status' : TransferStatus,
    'direction' : TransferDirection,
    'asset' : TransferAsset,
    'createdAt' : Timestamp,
    'counterparty' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const PositionBasis = IDL.Record({
    'winningAmount' : Lucky,
    'locked' : IDL.Bool,
    'winningDigit' : Digit,
    'digitAmounts' : IDL.Vec(Lucky),
    'position' : Position,
  });
  const RoundHistoryEntry = IDL.Record({
    'winningNumber' : BetNumber,
    'totalDistributed' : Lucky,
    'crowdfundTotal' : Lucky,
    'totalPrizePool' : Lucky,
    'positions' : IDL.Vec(PositionBasis),
    'finishedAt' : Timestamp,
    'round' : IDL.Nat,
  });
  const TokenMetadata = IDL.Record({
    'fee' : Lucky,
    'decimals' : IDL.Nat8,
    'logo' : IDL.Text,
    'name' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const TokenInfo = IDL.Record({
    'metadata' : TokenMetadata,
    'totalSupply' : Lucky,
  });
  const TopBetNumber = IDL.Record({
    'ticketCount' : IDL.Nat,
    'number' : BetNumber,
  });
  const WalletBalances = IDL.Record({
    'icpFeeE8s' : IcpE8s,
    'icpE8s' : IcpE8s,
    'lucky' : Lucky,
  });
  const Account = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const MetadataValue = IDL.Variant({
    'Int' : IDL.Int,
    'Nat' : IDL.Nat,
    'Blob' : IDL.Vec(IDL.Nat8),
    'Text' : IDL.Text,
  });
  const MetadataEntry = IDL.Record({
    'key' : IDL.Text,
    'value' : MetadataValue,
  });
  const SupportedStandard = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const TransferArg = IDL.Record({
    'to' : Account,
    'fee' : IDL.Opt(Lucky),
    'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'from_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'created_at_time' : IDL.Opt(IDL.Nat64),
    'amount' : Lucky,
  });
  const TransferError = IDL.Variant({
    'GenericError' : IDL.Record({
      'message' : IDL.Text,
      'error_code' : IDL.Nat,
    }),
    'TemporarilyUnavailable' : IDL.Null,
    'BadBurn' : IDL.Record({ 'min_burn_amount' : Lucky }),
    'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
    'BadFee' : IDL.Record({ 'expected_fee' : Lucky }),
    'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
    'TooOld' : IDL.Null,
    'InsufficientFunds' : IDL.Record({ 'balance' : Lucky }),
  });
  const TransferResult = IDL.Variant({ 'Ok' : IDL.Nat, 'Err' : TransferError });
  const AllowanceArg = IDL.Record({ 'account' : Account, 'spender' : Account });
  const Allowance = IDL.Record({
    'allowance' : Lucky,
    'expires_at' : IDL.Opt(IDL.Nat64),
  });
  const ApproveArg = IDL.Record({
    'fee' : IDL.Opt(Lucky),
    'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'from_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'created_at_time' : IDL.Opt(IDL.Nat64),
    'amount' : Lucky,
    'expected_allowance' : IDL.Opt(Lucky),
    'expires_at' : IDL.Opt(IDL.Nat64),
    'spender' : Account,
  });
  const ApproveError = IDL.Variant({
    'GenericError' : IDL.Record({
      'message' : IDL.Text,
      'error_code' : IDL.Nat,
    }),
    'TemporarilyUnavailable' : IDL.Null,
    'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
    'BadFee' : IDL.Record({ 'expected_fee' : Lucky }),
    'AllowanceChanged' : IDL.Record({ 'current_allowance' : Lucky }),
    'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
    'TooOld' : IDL.Null,
    'Expired' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
    'InsufficientFunds' : IDL.Record({ 'balance' : Lucky }),
  });
  const ApproveResult = IDL.Variant({ 'Ok' : IDL.Nat, 'Err' : ApproveError });
  const TransferFromArg = IDL.Record({
    'to' : Account,
    'fee' : IDL.Opt(Lucky),
    'spender_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'from' : Account,
    'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'created_at_time' : IDL.Opt(IDL.Nat64),
    'amount' : Lucky,
  });
  const TransferFromError = IDL.Variant({
    'GenericError' : IDL.Record({
      'message' : IDL.Text,
      'error_code' : IDL.Nat,
    }),
    'TemporarilyUnavailable' : IDL.Null,
    'InsufficientAllowance' : IDL.Record({ 'allowance' : Lucky }),
    'BadBurn' : IDL.Record({ 'min_burn_amount' : Lucky }),
    'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
    'BadFee' : IDL.Record({ 'expected_fee' : Lucky }),
    'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
    'TooOld' : IDL.Null,
    'InsufficientFunds' : IDL.Record({ 'balance' : Lucky }),
  });
  const TransferFromResult = IDL.Variant({
    'Ok' : IDL.Nat,
    'Err' : TransferFromError,
  });
  const TransactionKind = IDL.Variant({
    'transferFrom' : IDL.Null,
    'mint' : IDL.Null,
    'approve' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'to' : IDL.Opt(Account),
    'fee' : Lucky,
    'from' : IDL.Opt(Account),
    'kind' : TransactionKind,
    'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'timestamp' : Timestamp,
    'index' : IDL.Nat,
    'amount' : Lucky,
  });
  const BlockPage = IDL.Record({
    'nextIndex' : IDL.Opt(IDL.Nat),
    'transactions' : IDL.Vec(Transaction),
  });
  const AdminUserListOutcome = IDL.Variant({
    'ok' : IDL.Vec(AdminUserEntry),
    'err' : GameError,
  });
  const MigrateBalanceArg = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const MigrateBalanceResult = IDL.Record({
    'to' : Account,
    'totalSupply' : Lucky,
    'blockIndex' : IDL.Nat,
    'amount' : Lucky,
  });
  const MigrateBalanceOutcome = IDL.Variant({
    'ok' : MigrateBalanceResult,
    'err' : GameError,
  });
  const MintArg = IDL.Record({
    'to' : Account,
    'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'amount' : Lucky,
  });
  const MintResult = IDL.Record({
    'to' : Account,
    'totalSupply' : Lucky,
    'blockIndex' : IDL.Nat,
    'amount' : Lucky,
  });
  const MintOutcome = IDL.Variant({ 'ok' : MintResult, 'err' : GameError });
  const AdminResetResult = IDL.Record({
    'playersCleared' : IDL.Nat,
    'round' : IDL.Nat,
  });
  const AdminResetOutcome = IDL.Variant({
    'ok' : AdminResetResult,
    'err' : GameError,
  });
  const AdminPool = IDL.Variant({
    'exchangeIcp' : IDL.Null,
    'prizePool' : IDL.Null,
    'treasury' : IDL.Null,
    'exchangeLucky' : IDL.Null,
  });
  const AdminWithdrawResult = IDL.Record({
    'pool' : AdminPool,
    'recipient' : IDL.Principal,
    'remaining' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const AdminWithdrawOutcome = IDL.Variant({
    'ok' : AdminWithdrawResult,
    'err' : GameError,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'contributeCrowdfund' : IDL.Func([Position, Digit, Lucky], [GameError], []),
    'demoteToUser' : IDL.Func([IDL.Principal], [AdminRoleChangeOutcome], []),
    'devAdvanceRound' : IDL.Func([], [GameError], []),
    'devSeedBalance' : IDL.Func([IDL.Nat], [GameError], []),
    'devSetRoundElapsed' : IDL.Func([IDL.Int], [GameError], []),
    'exchangeIcpToLucky' : IDL.Func([IcpE8s], [GameError], []),
    'exchangeLuckyToIcp' : IDL.Func([Lucky], [GameError], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAdminStatus' : IDL.Func([], [AdminStatus], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyStats' : IDL.Func(
        [IDL.Text, IDL.Text],
        [DailyStatsOutcome],
        ['query'],
      ),
    'getDepositAddress' : IDL.Func([], [DepositAddress], ['query']),
    'getDrawResult' : IDL.Func([IDL.Nat], [IDL.Opt(DrawResult)], ['query']),
    'getExchangePoolState' : IDL.Func([], [ExchangePoolState], ['query']),
    'getGameState' : IDL.Func([], [GameState], ['query']),
    'getGuideText' : IDL.Func([], [GuideText], ['query']),
    'getLedgerBalance' : IDL.Func([], [LedgerBalance], ['query']),
    'getMyBetHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [BetHistoryPage],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [PlayerProfile], ['query']),
    'getMyWinHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [WinHistoryPage],
        ['query'],
      ),
    'getRecentTransfers' : IDL.Func(
        [],
        [IDL.Vec(WalletTransferRecord)],
        ['query'],
      ),
    'getRoundHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RoundHistoryEntry)],
        ['query'],
      ),
    'getTokenInfo' : IDL.Func([], [TokenInfo], ['query']),
    'getTopBetNumbers' : IDL.Func([], [IDL.Vec(TopBetNumber)], ['query']),
    'getTreasuryBalance' : IDL.Func([], [Lucky], ['query']),
    'getWalletBalances' : IDL.Func([], [WalletBalances], []),
    'icrc1_balance_of' : IDL.Func([Account], [Lucky], ['query']),
    'icrc1_decimals' : IDL.Func([], [IDL.Nat8], ['query']),
    'icrc1_fee' : IDL.Func([], [Lucky], ['query']),
    'icrc1_metadata' : IDL.Func([], [IDL.Vec(MetadataEntry)], ['query']),
    'icrc1_name' : IDL.Func([], [IDL.Text], ['query']),
    'icrc1_supported_standards' : IDL.Func(
        [],
        [IDL.Vec(SupportedStandard)],
        ['query'],
      ),
    'icrc1_symbol' : IDL.Func([], [IDL.Text], ['query']),
    'icrc1_total_supply' : IDL.Func([], [Lucky], ['query']),
    'icrc1_transfer' : IDL.Func([TransferArg], [TransferResult], []),
    'icrc2_allowance' : IDL.Func([AllowanceArg], [Allowance], ['query']),
    'icrc2_approve' : IDL.Func([ApproveArg], [ApproveResult], []),
    'icrc2_transfer_from' : IDL.Func(
        [TransferFromArg],
        [TransferFromResult],
        [],
      ),
    'icrc3_get_blocks' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(Account)],
        [BlockPage],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerController' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func([], [AdminUserListOutcome], ['query']),
    'migrateInternalLucky' : IDL.Func(
        [MigrateBalanceArg],
        [MigrateBalanceOutcome],
        [],
      ),
    'mintLucky' : IDL.Func([MintArg], [MintOutcome], []),
    'placeBet' : IDL.Func([BetNumber, IDL.Nat], [GameError], []),
    'placeBetSelections' : IDL.Func(
        [IDL.Vec(IDL.Vec(Digit)), IDL.Vec(IDL.Nat)],
        [GameError],
        [],
      ),
    'placeBets' : IDL.Func(
        [IDL.Vec(BetNumber), IDL.Vec(IDL.Nat)],
        [GameError],
        [],
      ),
    'promoteToAdmin' : IDL.Func([IDL.Principal], [AdminRoleChangeOutcome], []),
    'resetGameData' : IDL.Func([], [AdminResetOutcome], []),
    'resumeRound' : IDL.Func([], [GameError], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setGuideText' : IDL.Func([IDL.Text], [GameError], []),
    'stopNextRound' : IDL.Func([], [GameError], []),
    'transferIcp' : IDL.Func([IDL.Principal, IcpE8s], [GameError], []),
    'transferLucky' : IDL.Func([IDL.Principal, Lucky], [GameError], []),
    'withdrawFromPool' : IDL.Func(
        [AdminPool, IDL.Nat, IDL.Principal],
        [AdminWithdrawOutcome],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };